List<String> allFestival = [
  'Makar Sakranti',
  'Pongal',
  'Basant Panchami',
  'Maha Shivratri',
  'Navratri',
  'Durga Puja',
  'Holi',
  'Baisakhi',
  // 'Thrissur Pooram',
  'Buddha Jayanti',
  'Eid Ul Fitr',
  'Ratha Yatra',
  'Raksha Bandhan',
  'Janmashtmi',
  'Independence Day',
  'Onam',
  'Ganesh Chaturthi',
  'Dussehra',
  'Diwali',
  'Gurupurab',
  'Christmas',
];
